"""
Data models for scheduler persistence.

All timestamps are stored as UTC epoch seconds (integers) for consistency.
"""

import json
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class IntervalCadence:
    """S5.2 Typed Cadence: the existing 'every:<seconds>' shape, given a
    real type. See docs/S5_2_TYPED_CADENCE_DESIGN.md Sec 3."""

    seconds: int


@dataclass(frozen=True)
class WindowCadence:
    """S5.2 Typed Cadence: the existing 'window:<seconds>:<times>' shape,
    given a real type. See docs/S5_2_TYPED_CADENCE_DESIGN.md Sec 3."""

    window_seconds: int
    times: int


@dataclass(frozen=True)
class DailyCadence:
    """S5.2 Typed Cadence: fire once per wall-clock day at hour:minute, in
    the daemon's configured timezone (KernelDaemon.tz, config/kernel.yaml's
    `timezone` key). See docs/S5_2_TYPED_CADENCE_DESIGN.md Sec 3/4."""

    hour: int  # 0-23
    minute: int  # 0-59


@dataclass(frozen=True)
class WeeklyCadence:
    """S5.2 Typed Cadence: fire once per wall-clock week at
    day_of_week/hour:minute, in the daemon's configured timezone. See
    docs/S5_2_TYPED_CADENCE_DESIGN.md Sec 3/4."""

    day_of_week: int  # 0=Monday .. 6=Sunday (Python date.weekday() convention)
    hour: int
    minute: int


Cadence = IntervalCadence | WindowCadence | DailyCadence | WeeklyCadence


@dataclass
class Tick:
    """Record of a single drive execution."""

    id: int | None = None
    task_id: str = ""
    started_ts: int = 0  # UTC epoch seconds
    finished_ts: int | None = None  # UTC epoch seconds
    success: int = 0  # 0 or 1
    idempotency_key: str = ""
    result_meta: str | None = None  # JSON string

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "task_id": self.task_id,
            "started_ts": self.started_ts,
            "finished_ts": self.finished_ts,
            "success": self.success,
            "idempotency_key": self.idempotency_key,
            "result_meta": json.loads(self.result_meta) if self.result_meta else None,
        }


@dataclass
class Nudge:
    """
    Proactive suggestion emitted by a drive.

    Reuses existing nudges table schema from MemoryStore.
    """

    kind: str
    message: str
    actions: list[dict[str, Any]]
    reason: str
    created_ts: int  # UTC epoch seconds

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "kind": self.kind,
            "message": self.message,
            "actions": self.actions,
            "reason": self.reason,
            "created_ts": self.created_ts,
        }


@dataclass
class Reflection:
    """
    Reflective content generated by a drive.

    Reuses existing reflections table schema from MemoryStore.
    """

    kind: str
    content: str
    meta: dict[str, Any] | None
    ts: int  # UTC epoch seconds
    pinned: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "kind": self.kind,
            "content": self.content,
            "meta": self.meta,
            "ts": self.ts,
            "pinned": self.pinned,
        }
